-- MySQL Script generated by MySQL Workbench
-- Fri Oct 11 11:03:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library_management` ;

-- -----------------------------------------------------
-- Table `library_management`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `profile_image` MEDIUMBLOB NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `gender` ENUM('Male', 'Female', 'Other') NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `published_year` YEAR NULL DEFAULT NULL,
  `genre_name` VARCHAR(255) NULL DEFAULT NULL,
  `book_code` VARCHAR(50) NOT NULL,
  `stock` INT NOT NULL,
  `price` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`borrowing_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`borrowing_cards` (
  `borrowing_card_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `gender` ENUM('Male', 'Female', 'Other') NULL DEFAULT NULL,
  `borrowing_card_code` VARCHAR(50) NOT NULL,
  `deposit` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` INT NULL DEFAULT '0',
  PRIMARY KEY (`borrowing_card_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`borrowing_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`borrowing_records` (
  `borrowing_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `borrowing_card_id` INT NOT NULL,
  `borrow_date` DATE NOT NULL,
  `return_date` DATE NULL DEFAULT NULL,
  `due_date` DATE NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` ENUM('active', 'returned', 'overdue') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`borrowing_id`),
  INDEX `book_id` (`book_id` ASC) VISIBLE,
  INDEX `borrowing_records_ibfk_2_idx` (`borrowing_card_id` ASC) VISIBLE,
  CONSTRAINT `borrowing_records_ibfk_1`
    FOREIGN KEY (`book_id`)
    REFERENCES `library_management`.`books` (`book_id`),
  CONSTRAINT `borrowing_records_ibfk_2`
    FOREIGN KEY (`borrowing_card_id`)
    REFERENCES `library_management`.`borrowing_cards` (`borrowing_card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('pending', 'paid', 'refunded') NOT NULL DEFAULT 'pending',
  `invoice_code` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`readers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`readers` (
  `reader_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `dob` DATE NULL DEFAULT NULL,
  `gender` ENUM('Male', 'Female', 'Other') NULL DEFAULT NULL,
  `citizenship_card` VARCHAR(20) NULL DEFAULT NULL,
  `reader_code` VARCHAR(50) NOT NULL,
  `expiry_date` DATE NOT NULL,
  `status` INT NULL DEFAULT '0',
  PRIMARY KEY (`reader_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`payment_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`payment_details` (
  `payment_detail_id` INT NOT NULL AUTO_INCREMENT,
  `payment_id` INT NOT NULL,
  `payment_type` ENUM('reader_card', 'borrowing_card', 'refund_deposit') NOT NULL,
  `borrowing_card_id` INT NULL DEFAULT NULL,
  `reader_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_detail_id`),
  INDEX `payment_id` (`payment_id` ASC) VISIBLE,
  INDEX `borrowing_card_id` (`borrowing_card_id` ASC) VISIBLE,
  INDEX `reader_id` (`reader_id` ASC) VISIBLE,
  CONSTRAINT `payment_details_ibfk_1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `library_management`.`payments` (`payment_id`),
  CONSTRAINT `payment_details_ibfk_2`
    FOREIGN KEY (`borrowing_card_id`)
    REFERENCES `library_management`.`borrowing_cards` (`borrowing_card_id`),
  CONSTRAINT `payment_details_ibfk_3`
    FOREIGN KEY (`reader_id`)
    REFERENCES `library_management`.`readers` (`reader_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `library_management`.`return_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_management`.`return_entries` (
  `return_id` INT NOT NULL AUTO_INCREMENT,
  `borrowing_id` INT NOT NULL,
  `return_date` DATE NOT NULL,
  `late_days` INT NULL DEFAULT '0',
  `book_condition` ENUM('good', 'damaged', 'lost') NOT NULL DEFAULT 'good',
  `fine` DECIMAL(10,2) NULL DEFAULT '0.00',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`return_id`),
  INDEX `borrowing_id` (`borrowing_id` ASC) VISIBLE,
  CONSTRAINT `return_entries_ibfk_1`
    FOREIGN KEY (`borrowing_id`)
    REFERENCES `library_management`.`borrowing_records` (`borrowing_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
